[package]
name = "solana-rust-contract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.9"
solana-program = "=1.10.8"
thiserror = "1.0"

[lib]
crate-type = ["cdylib", "lib"]